### ISSUE TITLE
Unexpected attribute

### ISSUE THREAD

**Issue by sonicvlada** [Donovand4/ConditionalAccessPolicyReport#14]
Hi, thank you for sharing this.
This is the error I'm getting after I run the ".\Generate-ConditionalAccessReport.ps1 -OutputFormat CSV -BetaProfile $true" command:
I couldn't find anything in the comments, and my PS skills are not good enough to troubleshoot.

```
At C:\scripts\Generate-ConditionalAccessReport.ps1:71 char:1
+ [CmdletBinding()]
+ ~~~~~~~~~~~~~~~~~
Unexpected attribute 'CmdletBinding'.
At C:\scripts\Generate-ConditionalAccessReport.ps1:72 char:1
+ param (
+ ~~~~~
Unexpected token 'param' in expression or statement.
    + CategoryInfo          : ParserError: (:) [], ParseException
    + FullyQualifiedErrorId : UnexpectedAttribute
```

**Comment by Donovand4** [comment]
Hi, 
I had to remove the beta profile as it was delaying the login and caused additional problems. 
Please download the latest version and run the updated commands.

**Comment by Donovand4** [comment]
Beta profile has been added which uses the latest modules

**Comment by Donovand4** [comment]
Beta profile has been added which uses the latest modules and resolves the errors experienced
