### ISSUE TITLE
LocationExcludeLocations reporting blank when it should state All Trusted locations

### ISSUE THREAD

**Issue by SvenBell** [Donovand4/ConditionalAccessPolicyReport#16]
Output LocationExcludeLocations reporting blank when it should state All Trusted locations

It would also be beneficial if all Named locations could also be output as another section of the report or separate file for reference

Thank you for sharing this script, much appreciated.

**Comment by Donovand4** [comment]
Thank you for the feedback, will have a look at what can be done.

**Comment by Donovand4** [comment]
Updated version released that includes the All Trusted Locations.

**Comment by Donovand4** [comment]
Closing this issue, new enhancement raised for the named locations report. Issue number #17
