### ISSUE TITLE
issues with Connect-MsGraph

### ISSUE THREAD

**Issue by beigewell** [Donovand4/ConditionalAccessPolicyReport#2]
I would just add it's worth using POSH 7 as it prompts for MFA better. It also took about 3 runs for the device login to graph to be accepted before it ran correctly. I got prompted for a couple of different permissions on the first two attempts. Working sweetly now!

**Comment by Donovand4** [comment]
Thank you for the info and I am glad it's now working. I will be updating the repo to include a getting started section.

**Comment by beigewell** [comment]
I also uncommented the install-module line at the beginning and ran smoother. I have a feeling the issues were more to do with the graph module being preview than the script. My issues were all to do with getting the authentication to hold through the session.

**Comment by Donovand4** [comment]
Yes, the modules are a must so I will add that to the getting started section as well.
