### ISSUE TITLE
ConditionalAccessPolicyReport

### ISSUE THREAD

**Issue by Sittampalam** [Donovand4/ConditionalAccessPolicyReport#8]
Hello
I been through the steps and all seem to work without any issues burt when I run the script it complains about

PS C:\source\graphnet\ConditionalAccessPolicyReport-master> Connect-Graph -Scopes "Policy.Read.All","Directory.Read.All"
Welcome To Microsoft Graph!
PS C:\source\graphnet\ConditionalAccessPolicyReport-master> .\Generate-ConditionalAccessReport.ps1 -export All          
Security warning
Run only scripts that you trust. While scripts from the internet can be useful, this script can potentially harm your
computer. If you trust this script, use the Unblock-File cmdlet to allow the script to run without this warning
message. Do you want to run
C:\source\graphnet\ConditionalAccessPolicyReport-master\Generate-ConditionalAccessReport.ps1?
[D] Do not run  [R] Run once  [S] Suspend  [?] Help (default is "D"): R
.\Generate-ConditionalAccessReport.ps1 : The script 'Generate-ConditionalAccessReport.ps1' cannot be run because the
following modules that are specified by the "#requires" statements of the script are missing:
Microsoft.Graph.Identity.RoleManagement.
At line:1 char:1
+ .\Generate-ConditionalAccessReport.ps1 -export All
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ResourceUnavailable: (Generate-ConditionalAccessReport.ps1:String) [], ScriptRequiresExc
   eption
    + FullyQualifiedErrorId : ScriptRequiresMissingModules

PS C:\source\graphnet\ConditionalAccessPolicyReport-master>

Any idea why the modules is not there?

**Comment by Donovand4** [comment]
Hello,
It appears as if the module is not installed. The below would install the latest Microsoft.Graph.Identity.RoleManagement module.

Install-Module -Name Microsoft.Graph.Identity.RoleManagement

If the module is installed, then perhaps the module would need to be imported manually from the location where it is installed.
