### ISSUE TITLE
Microsoft.Graph.Identity.RoleManagement no longer found

### ISSUE THREAD

**Issue by thetootall** [Donovand4/ConditionalAccessPolicyReport#9]
Install-Module -Name Microsoft.Graph.Identity.RoleManagement
PackageManagement\Install-Package : No match was found for the specified search criteria and module name

**Comment by Donovand4** [comment]
Thank you for raising the issue. It appears as if the module has been completely deprecated. I will update the script and remove references to it.

**Comment by Donovand4** [comment]
Removed legacy modules and reporting details for it.
Thank you @thetootall for the finding
